### ISSUE TITLE
diameterc: Command not found

### ISSUE THREAD

**Issue by laipham** [sigscale/ocs#1]
I run "make" and get error
[root@localhost ocs.build]# make check
Making check in include
make[1]: Entering directory `/home/lai/ocs.build/include'
diameterc -E ../../ocs-master/src/nas_application_rfc7155.dia
make[1]: diameterc: Command not found
make[1]: *** [diameter_gen_nas_application_rfc7155.hrl] Error 127
make[1]: Leaving directory `/home/lai/ocs.build/include'
make: *** [check-recursive] Error 1

I use diameter 1.15

**Comment by kalpacg** [comment]
@laipham what is your Erlang OTP version and on what platfotrm this occured ?

**Comment by kalpacg** [comment]
@laipham The problem seems to be diameterc is not in your path and it tries to process .dia files. Try reconfiguring the project with the recent changes I have pushed to github repo. OTP 18,19 and diameter versions higher than 1.11.2 are tested and works well.

**Comment by laipham** [comment]
Thank you. It works for me. :dancing_men:

**Comment by kalpacg** [comment]
Issue resolved therefore closing it.
